version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '12:00'
  labels:
  - dependabot
  - dependencies
  ignore:
  - dependency-name: convict
    versions:
    - ">= 6.0.a, < 6.1"
  - dependency-name: axios
    versions:
    - "0.20.0"
 
