version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '10:00'
  assignees:
  - MrBartusek
  labels:
  - dependabot
  - dependencies
  ignore:
  - dependency-name: convict
    versions:
    - ">= 6.0.a, < 6.1"
 
