version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build: 
    docker:
      - image: circleci/node:10.16.3 
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Instal NPM
          command: npm install
      - save_cache: # special step
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check Code Styling
          command: npm run lint
      - run:
          name: Run tests
          command: node_modules/.bin/jest --verbose --silent --ci --runInBand --collectCoverage=true --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit/js-test-results.xml
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/*.json

      
