version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:10.16.3 
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Instal NPM
          command: npm install
      - save_cache: # special step
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: 
          name: Build
          command: npm build
      - run:
          name: Check Tests
          command: npm test
      - run:
          name: Check Code Styling
          command: npm run lint
