version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

executors:
  node-executor:
    working_directory: ~/replacementBot
    docker:
      - image: 'circleci/node:lts'

jobs:
  prepare:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: Instal Dependencies
          command: npm ci
      - save_cache:
          key: 'dependency-cache-{{ checksum "package-lock.json" }}'
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/replacementBot
          paths:
            - node_modules

  test:
    executor: node-executor
    steps:
      - checkout:
          path: ~/replacementBot
      - attach_workspace:
          at: ~/replacementBot
      - run:
          name: Run tests
          command: >-
            ./node_modules/.bin/jest --verbose --silent --ci --runInBand
            --collectCoverage=true --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit/js-test-results.xml
      - store_test_results:
          path: reports/junit/js-test-results.xml
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/*.json

  lint:
    executor: node-executor
    steps:
      - checkout:
          path: ~/replacementBot
      - attach_workspace:
          at: ~/replacementBot
      - run:
          name: Check Code Styling
          command: npm run lint

  build:
    executor: node-executor
    steps:
      - checkout:
          path: ~/replacementBot
      - attach_workspace:
          at: ~/replacementBot
      - run:
          name: Build Typescript
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
