version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

executors:
  node-executor:
    working_directory: ~/replacementBot
    docker:
      - image: circleci/node:latest

jobs:
  build: 
    executor: node-executor
    steps:

      - checkout

      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Instal NPM
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/replacementBot
          paths:
            - node_modules

  lint:
    executor: node-executor
    steps:
      - checkout:
        path: ~/replacementBot

      - attach_workspace:
        at: ~/replacementBot

      - run:
        name: Check Code Styling
        command: npm run lint

  test:
    executor: node-executor
    steps:

    - checkout:
      path: ~/replacementBot

    - attach_workspace:
        at: ~/replacementBot

    - run:
        name: Run tests
        command: ./node_modules/.bin/jest --verbose --silent --ci --runInBand --collectCoverage=true --reporters=default --reporters=jest-junit
        environment:
          JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

    - store_test_results:
        path: reports/junit/js-test-results.xml

    - store_artifacts:
        path: coverage

    - codecov/upload:
        file: coverage/*.json

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build